import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rootDir = path.resolve(__dirname, '..');
const distDir = path.join(rootDir, 'dist');
const themeDir = path.join(rootDir, '../theme_build');
const themeAssetsDir = path.join(themeDir, 'assets');

console.log('📦 Preparing WordPress Theme...');

// 1. Check if build exists
if (!fs.existsSync(distDir)) {
    console.error('❌ Build directory not found! Run "npm run build" first.');
    process.exit(1);
}

// 2. Clear old assets in theme_build
if (fs.existsSync(themeAssetsDir)) {
    console.log('🧹 Clearing old theme assets...');
    fs.rmSync(themeAssetsDir, { recursive: true, force: true });
}
fs.mkdirSync(themeAssetsDir, { recursive: true });

// 3. Copy new assets
console.log('📂 Copying new assets to theme folder...');
fs.cpSync(path.join(distDir, 'assets'), themeAssetsDir, { recursive: true });

// Copy robots.txt and sitemap.xml to theme root
const publicFiles = ['robots.txt', 'sitemap.xml'];
publicFiles.forEach(file => {
    const srcPath = path.join(distDir, file);
    const destPath = path.join(themeDir, file);
    if (fs.existsSync(srcPath)) {
        fs.copyFileSync(srcPath, destPath);
        console.log(`📄 Copied ${file} to theme folder`);
    }
});

// 4. Verify Core Theme Files & Inject Dynamic Asset Names
const functionsPath = path.join(themeDir, 'functions.php');
const requiredFiles = ['index.php', 'functions.php', 'style.css', '.htaccess'];
const missingFiles = requiredFiles.filter(f => !fs.existsSync(path.join(themeDir, f)));

if (missingFiles.length > 0) {
    console.warn(`⚠️ Warning: Missing core theme files: ${missingFiles.join(', ')}`);
} else {
    console.log('✅ Core theme files present.');

    // Inject hashed filenames into functions.php to force cache breaking
    let functionsContent = fs.readFileSync(functionsPath, 'utf8');

    // Find the actual hashed JS and CSS files generated by Vite
    const assetsFiles = fs.readdirSync(themeAssetsDir);
    const jsFile = assetsFiles.find(f => f.startsWith('index-') && f.endsWith('.js')) || 'index.js';
    const cssFile = assetsFiles.find(f => f.startsWith('index-') && f.endsWith('.css')) || 'index.css';

    // Replace old enqueue paths in functions.php with the new hashed file names
    functionsContent = functionsContent.replace(/\$theme_dir \. '\/assets\/index.*?\.css'/g, `$theme_dir . '/assets/${cssFile}'`);
    functionsContent = functionsContent.replace(/\$theme_uri \. '\/assets\/index.*?\.css'/g, `$theme_uri . '/assets/${cssFile}'`);
    functionsContent = functionsContent.replace(/\$theme_dir \. '\/assets\/index.*?\.js'/g, `$theme_dir . '/assets/${jsFile}'`);
    functionsContent = functionsContent.replace(/\$theme_uri \. '\/assets\/index.*?\.js'/g, `$theme_uri . '/assets/${jsFile}'`);

    fs.writeFileSync(functionsPath, functionsContent);
    console.log(`🔗 Injected dynamic assets into functions.php: ${jsFile}, ${cssFile}`);
}

console.log(`
🎉 Theme Package Ready!
---------------------------------------------------
Location: ${themeDir}

Next Steps:
1. Go to "theme_build" folder.
2. Select all files (assets, index.php, style.css, etc).
3. Right-click -> "Compress to ZIP file".
4. Upload to WordPress.
---------------------------------------------------
`);
